# Generated by Django 3.0 on 2020-10-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_of_measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasurement',
            old_name='measurement_type',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='unitofmeasurement',
            old_name='name',
            new_name='type_of_measurement',
        ),
        migrations.AddField(
            model_name='unitofmeasurement',
            name='unit_of_meaurement',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
