# Generated by Django 3.0 on 2020-10-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_of_measurement', '0002_auto_20201007_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasurement',
            old_name='unit_of_meaurement',
            new_name='unit_of_measurement',
        ),
    ]
