# Generated by Django 3.0 on 2020-10-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
