# Generated by Django 3.0 on 2020-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='mobile',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
