# Generated by Django 3.0 on 2020-10-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20201024_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
