# Generated by Django 3.0 on 2020-02-12 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('account', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('stock_type', models.CharField(choices=[('Box', 'box'), ('Bundle', 'bundle')], max_length=100)),
                ('bulkmode', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('current', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productstock', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk', models.BooleanField(default=False)),
                ('sell_rate', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('cash_rounded_off', models.IntegerField(default=0)),
                ('cash_received', models.IntegerField()),
                ('profit', models.IntegerField(blank=True, null=True)),
                ('sell_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                # ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsell', to='account.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productSell', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk', models.BooleanField(default=False)),
                ('buy_rate', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productpurchase', to='product.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productpurchase', to='supplier.Supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productpurchase', to='warehouse.WareHouse')),
            ],
        ),
    ]
