# Generated by Django 3.0 on 2020-02-13 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200213_1020'),
        ('inventory', '0003_auto_20200212_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderItem', to='product.Product'),
        ),
    ]
