# Generated by Django 3.0 on 2020-02-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('tag', models.CharField(max_length=250)),
                ('remarks', models.TextField(null=True)),
                ('default_price', models.IntegerField(blank=True, null=True)),
                ('default_mrp', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Category')),
                ('gstcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='tax.GSTCode')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('measurement_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_piece_buy_rate', models.IntegerField(blank=True, null=True)),
                ('per_bulk_buy_rate', models.IntegerField(blank=True, null=True)),
                ('per_piece_sell_rate', models.IntegerField(blank=True, null=True)),
                ('per_bulk_sell_rate', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('current', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rate', to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='unit_of_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='product.UnitOfMeasurement'),
        ),
    ]
