# Generated by Django 3.0 on 2020-10-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maximumretailprice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcostprice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsaleprice',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
