# Generated by Django 3.0 on 2020-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201024_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasurement',
            old_name='measurement_type',
            new_name='type_of_measurement',
        ),
        migrations.RenameField(
            model_name='unitofmeasurement',
            old_name='name',
            new_name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='unitofmeasurement',
            name='abbreviation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
