# Generated by Django 3.0 on 2020-02-13 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productcostprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSalePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_piece_sell_price', models.IntegerField(blank=True, null=True)),
                ('per_bulk_sell_price', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('current', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productbuyrate', to='product.Product')),
            ],
        ),
    ]
