# Generated by Django 3.0 on 2020-02-14 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productsaleprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRate',
        ),
    ]
