# Generated by Django 3.0 on 2020-07-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_productrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsaleprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productsalerate', to='product.Product'),
        ),
    ]
