# Generated by Django 3.0 on 2020-08-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200720_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='default_mrp',
            new_name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_price',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
