# Generated by Django 3.0 on 2020-08-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200804_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='abbrebiation',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
