# Generated by Django 3.0 on 2020-08-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_abbrebiation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='abbrebiation',
            new_name='abbreviation',
        ),
    ]
