# Generated by Django 3.0 on 2020-08-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200808_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
