# Generated by Django 3.0 on 2020-08-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='remarks',
            new_name='description',
        ),
    ]
