# Generated by Django 3.0 on 2020-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
                ('remarks', models.CharField(max_length=250)),
            ],
        ),
    ]
