# Generated by Django 3.0 on 2020-10-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gstcode',
            old_name='description',
            new_name='description_of_good',
        ),
    ]
