# Generated by Django 3.0 on 2020-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_auto_20200823_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstcode',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
