# Generated by Django 3.0 on 2020-08-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_auto_20200823_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstcode',
            name='totalGst',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
