# Generated by Django 3.0 on 2020-08-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_auto_20200830_1700'),
        ('tax', '0005_auto_20200830_1613'),
    ]

    operations = [
    ]
