# Generated by Django 3.0 on 2020-10-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='retailmode',
            field=models.BooleanField(default=False),
        ),
    ]
