# Generated by Django 3.0 on 2020-10-27 06:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_purchaseorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 27, 6, 19, 30, 161503, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
