# Generated by Django 3.0 on 2020-10-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('transaction', '0002_productstock_retailmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='time',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='warehouse',
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=255)),
                ('total_tax', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productpurchase', to='supplier.Supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productpurchase', to='warehouse.WareHouse')),
            ],
        ),
    ]
