# Generated by Django 3.0 on 2020-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20201026_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='cost_price_bulk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sell_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sell_price_bulk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='cost_price',
            field=models.FloatField(),
        ),
    ]
