# Generated by Django 3.0 on 2020-10-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_purchaseorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='bulk',
            field=models.BooleanField(default=False),
        ),
    ]
