# Generated by Django 3.0 on 2020-10-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_purchaseorderitem_bulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
