# Generated by Django 3.0 on 2020-10-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20201026_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item', to='transaction.PurchaseOrder'),
            preserve_default=False,
        ),
    ]
