# Generated by Django 3.0 on 2020-10-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_purchaseorderitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
