# Generated by Django 3.0 on 2020-10-26 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201026_0152'),
        ('customer', '0001_initial'),
        ('transaction', '0005_purchaseorderitem_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total_discount', models.IntegerField(default=0)),
                ('total_tax', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='customer.Customer')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='transaction.ModeOfSell')),
            ],
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='discount',
            new_name='total_discount',
        ),
        migrations.CreateModel(
            name='SettleSellBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_amount', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settle_sell_bill', to='transaction.SellOrder')),
            ],
        ),
        migrations.CreateModel(
            name='SettlePurchaseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_amount', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settle_purchase_bill', to='transaction.PurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='SellOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('sell_price', models.IntegerField()),
                ('tax_code', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_price', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='transaction.SellOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderItem', to='product.Product')),
            ],
        ),
    ]
