# Generated by Django 3.0 on 2020-10-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_purchaseorderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='cost_price_bulk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
