# Generated by Django 3.0 on 2020-10-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20201026_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellorder',
            name='mode',
        ),
        migrations.AddField(
            model_name='sellorder',
            name='credit',
            field=models.BooleanField(default=False),
        ),
    ]
