# Generated by Django 3.0 on 2020-10-27 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20201026_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='bulk',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='cost_price_bulk',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='sell_price_bulk',
        ),
    ]
