# Generated by Django 3.0 on 2020-10-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_purchaseorderitem_cost_price_bulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sell_price_bulk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
