# Generated by Django 3.0 on 2020-10-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20201027_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_discount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_tax',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='warehouse',
        ),
    ]
