# Generated by Django 3.0 on 2020-10-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_purchaseorderitem_sell_price_bulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
