# Generated by Django 3.0 on 2020-10-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_purchaseorderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='cost_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
