# Generated by Django 3.0 on 2020-10-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_purchaseorderitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sell_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
