# Generated by Django 3.0 on 2020-10-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20201027_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='ref_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
