# Generated by Django 3.0 on 2020-02-14 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('discount_percentage', models.IntegerField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('contact_no', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=100)),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to='customer.CustomerType')),
            ],
        ),
    ]
