# Generated by Django 3.0 on 2020-09-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200720_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertype',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
