# Generated by Django 3.0 on 2020-09-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customertype_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address1',
            new_name='address',
        ),
    ]
