# Generated by Django 3.0 on 2020-10-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201024_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertype',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
