# Generated by Django 3.0 on 2020-10-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
