# Generated by Django 3.0 on 2020-09-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
