# Generated by Django 3.0 on 2020-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('taxable_amount', models.FloatField()),
                ('total_tax', models.FloatField()),
                ('invoice_total', models.FloatField()),
            ],
        ),
    ]
