# Generated by Django 3.0 on 2020-02-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0006_delete_productrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('sell_rate', models.IntegerField()),
                ('profit', models.IntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderItem', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=255)),
                ('discount', models.IntegerField(default=0)),
                ('cash_received', models.IntegerField()),
                ('cash_rounded_off', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('items', models.ManyToManyField(to='sell.OrderItem')),
            ],
        ),
    ]
