# Generated by Django 3.0 on 2020-09-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('discount', models.IntegerField(default=0)),
                ('totalTax', models.FloatField(blank=True, null=True)),
                ('cash_received', models.IntegerField()),
                ('cash_rounded_off', models.IntegerField(default=0)),
                ('returned', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('sell_rate', models.IntegerField()),
                ('profit', models.IntegerField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItem', to='sell.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderItem', to='product.Product')),
            ],
        ),
    ]
