# Generated by Django 3.0 on 2020-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_auto_20201024_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlebill',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
