# Generated by Django 3.0 on 2020-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20200720_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalTax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
