# Generated by Django 3.0 on 2020-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0008_auto_20201023_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tax_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
