# Generated by Django 3.0 on 2020-10-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0011_orderitem_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='total_discount',
        ),
    ]
