# Generated by Django 3.0 on 2020-10-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0012_auto_20201023_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalTax',
            new_name='total_tax',
        ),
    ]
