# Generated by Django 3.0 on 2020-10-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0013_auto_20201023_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=555, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='cash_rounded_off',
        ),
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
