# Generated by Django 3.0 on 2020-10-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200929_1502'),
        ('sell', '0014_auto_20201023_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='returned',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='sell.ModeOfSell'),
        ),
        migrations.CreateModel(
            name='SettleBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_amount', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settle_bill', to='sell.Order')),
            ],
        ),
    ]
